kind: ConfigMap 
apiVersion: v1 
metadata:
  name: env-configmap 
data:
  # Configuration values can be set as key-value properties
  AWS_BUCKET: arn:aws:s3:::my-mono-bucket
  AWS_REGION: us-east-1
  AWS_PROFILE: default
  JWT_SECRET: testing
  URL: http://localhost:8100
